name: Build

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          sudo apt update && sudo apt upgrade -y
          git clone https://github.com/ading2210/shimboot
          cd shimboot
          mkdir output
          sudo ./build_complete.sh dedede release=unstable desktop=gnome
          cd data
          sudo zip shimboot_dedede.zip shimboot_dedede.bin
          sudo mv shimboot_dedede.zip ../output
          cd ..
          sudo rm -rf data
          ls
          ls output
