name: Build

on: [push]

jobs:
  build_and_test:
    runs-on: debain-latest
    steps:
      - name: Build
        run: |
          git clone https://github.com/ading2210/shimboot
          cd shimboot
          sudo ./build_complete.sh dedede
          tree
